package handlers

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/f2cothai/f2-website/services/payment-api/internal/config"
	"github.com/f2cothai/f2-website/services/payment-api/internal/notify"
	"github.com/f2cothai/f2-website/services/payment-api/internal/paypal"
)

// SandboxHandler exposes test-only helpers when payment_settings.mode
// is 'sandbox'. The routes that mutate state are still admin-gated; the
// public status endpoint is unauthenticated so the frontend banner can
// render before login.
type SandboxHandler struct {
	DB     *pgxpool.Pool
	Cfg    config.Config
	Notify *notify.Client
	PayPal *paypal.Client
}

// PublicStatus is unauthenticated — anyone can read each method's mode.
// Used by the SandboxBanner component across portal + admin + public.
// Returns a map of method → mode plus a convenience `any_sandbox` flag
// so the banner can decide visibility cheaply.
func (h *SandboxHandler) PublicStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	modes, anySandbox := GetAllMethodModes(ctx, h.DB)
	writeJSON(w, 200, map[string]any{
		"methods":           modes,
		"any_sandbox":       anySandbox,
		"paypal_mode":       h.PayPal.ActiveMode(ctx),
		"paypal_configured": h.PayPal.Enabled(ctx),
	})
}

// AdminSeed creates (or reuses) a "F2 SANDBOX TEST" customer and issues
// a fresh draft invoice with two line items for exercising the pay flow.
// Idempotent on the customer (slug = sandbox-test); each call creates a
// NEW invoice so QA can spin up as many as they want.
//
// Available whenever ANY method is in sandbox — seeding produces only
// test data so it's safe regardless of which method an admin plans to
// test with.
func (h *SandboxHandler) AdminSeed(w http.ResponseWriter, r *http.Request) {
	if _, any := GetAllMethodModes(r.Context(), h.DB); !any {
		writeErr(w, 403, "no payment methods are in sandbox mode")
		return
	}

	// Optional currency — THB (default) or USD. Seed USD to get a
	// PayPal-payable invoice (PayPal rejects THB) for a repeatable live
	// click-through. Body is optional; a missing/blank currency = THB.
	var body struct {
		Currency string `json:"currency"`
	}
	_ = json.NewDecoder(r.Body).Decode(&body)
	currency := "THB"
	if strings.ToUpper(strings.TrimSpace(body.Currency)) == "USD" {
		currency = "USD"
	}

	ctx, cancel := makeCtx()
	defer cancel()

	tx, err := h.DB.Begin(ctx)
	if err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	defer tx.Rollback(ctx)

	// Ensure sandbox customer exists.
	var customerID string
	err = tx.QueryRow(ctx, `
		SELECT id FROM customers WHERE slug='sandbox-test'`).Scan(&customerID)
	if err != nil {
		// Create
		err = tx.QueryRow(ctx, `
			INSERT INTO customers (slug, name, industry, is_active, services_used, notes)
			VALUES ('sandbox-test', 'F2 SANDBOX TEST', 'sandbox', true,
			        ARRAY['domain-hosting','it-support-msp']::text[],
			        'Auto-generated by /api/payment/admin/sandbox/seed — safe to delete.')
			RETURNING id`).Scan(&customerID)
		if err != nil {
			writeErr(w, 500, "create sandbox customer: "+err.Error())
			return
		}
	}

	// Number the invoice
	var seq int64
	if err := tx.QueryRow(ctx, `SELECT nextval('invoice_number_seq')`).Scan(&seq); err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	number := fmt.Sprintf("SBX-%d-%06d", time.Now().Year(), seq)

	// Two test items totalling 1,500.00 THB before VAT.
	const (
		item1Cents int64 = 80000 // ฿800.00
		item2Cents int64 = 70000 // ฿700.00
	)
	subtotal := item1Cents + item2Cents
	const vatBP = 700
	vat := subtotal * vatBP / 10000
	total := subtotal + vat

	uid := userID(r)
	var creator any
	if uid != "" {
		creator = uid
	}

	var invID string
	err = tx.QueryRow(ctx, `
		INSERT INTO invoices (
			invoice_number, customer_id, status, currency,
			subtotal_cents, vat_rate_bp, vat_cents, total_cents,
			issue_date, due_date, notes, metadata, created_by
		) VALUES ($1,$2,'issued',$8,$3,$4,$5,$6,
		          CURRENT_DATE, CURRENT_DATE + INTERVAL '7 days',
		          'Sandbox test invoice', '{"sandbox":true}'::jsonb, $7)
		RETURNING id`,
		number, customerID, subtotal, vatBP, vat, total, creator, currency).Scan(&invID)
	if err != nil {
		writeErr(w, 500, "create invoice: "+err.Error())
		return
	}

	_, err = tx.Exec(ctx, `
		INSERT INTO invoice_items (
			invoice_id, product_type, description_en, description_th,
			quantity, unit_price_cents, total_cents, sort_order
		) VALUES
		  ($1, 'custom', 'SANDBOX: .com domain registration (1 year)',
		       'แซนด์บ็อกซ์: จดทะเบียนโดเมน .com (1 ปี)', 1, $2, $2, 0),
		  ($1, 'custom', 'SANDBOX: Hosting plan – Starter (1 month)',
		       'แซนด์บ็อกซ์: แพ็คเกจโฮสติ้ง Starter (1 เดือน)', 1, $3, $3, 1)`,
		invID, item1Cents, item2Cents)
	if err != nil {
		writeErr(w, 500, "create items: "+err.Error())
		return
	}

	if err := tx.Commit(ctx); err != nil {
		writeErr(w, 500, err.Error())
		return
	}

	writeJSON(w, 201, map[string]any{
		"invoice_id":     invID,
		"invoice_number": number,
		"customer_id":    customerID,
		"customer_name":  "F2 SANDBOX TEST",
		"total_cents":    total,
		"currency":       currency,
	})
}

// AdminCompletePayment skips PayPal/slip verification and forces a payment
// row to `completed`, reconciling its parent invoice. Use after starting
// a payment in the portal to short-circuit the flow.
func (h *SandboxHandler) AdminCompletePayment(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	uid := userID(r)
	var actor any
	if uid != "" {
		actor = uid
	}

	ctx, cancel := makeCtx()
	defer cancel()
	tx, err := h.DB.Begin(ctx)
	if err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	defer tx.Rollback(ctx)

	var status, method string
	if err := tx.QueryRow(ctx,
		`SELECT status, method FROM payments WHERE id=$1 FOR UPDATE`,
		id).Scan(&status, &method); err != nil {
		writeErr(w, 404, "payment not found")
		return
	}
	// Per-method gate — only allow force-completion when THIS payment's
	// method is in sandbox mode. Stops admin from accidentally bypassing
	// verification for a live bank_transfer.
	if GetMethodMode(ctx, h.DB, method) != "sandbox" {
		writeErr(w, 403, "method "+method+" is in production mode")
		return
	}
	if status == "completed" {
		writeJSON(w, 200, map[string]string{"status": "completed", "note": "already completed"})
		return
	}
	if _, err := tx.Exec(ctx, `
		UPDATE payments
		   SET status='completed', paid_at=NOW(),
		       verified_by_user_id=$1, verified_at=NOW(),
		       metadata = COALESCE(metadata, '{}'::jsonb) || jsonb_build_object('sandbox', true, 'sandbox_forced', true)
		 WHERE id=$2`, actor, id); err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	if err := reconcileInvoice(ctx, tx, id); err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	if err := tx.Commit(ctx); err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	writeJSON(w, 200, map[string]string{"status": "completed"})
}

// AdminSimulateWebhook fires the same internal completion path that the
// real PayPal webhook handler would. Takes a payment_id, finds its
// provider_order_id, and synthesises a CAPTURE.COMPLETED event row in
// payment_webhook_events plus reconciliation. Lets QA validate the
// completion path without configuring PayPal IPN delivery.
func (h *SandboxHandler) AdminSimulateWebhook(w http.ResponseWriter, r *http.Request) {
	if _, any := GetAllMethodModes(r.Context(), h.DB); !any {
		writeErr(w, 403, "no payment methods are in sandbox mode")
		return
	}
	id := chi.URLParam(r, "id")
	ctx, cancel := makeCtx()
	defer cancel()

	var (
		orderID string
		method  string
	)
	if err := h.DB.QueryRow(ctx,
		`SELECT COALESCE(provider_order_id,''), method FROM payments WHERE id=$1`,
		id).Scan(&orderID, &method); err != nil {
		writeErr(w, 404, "payment not found")
		return
	}
	if method != "paypal" {
		writeErr(w, 409, "payment is not a paypal payment")
		return
	}
	if orderID == "" {
		// Sandbox can fabricate an order id so the simulator works even when
		// PayPal isn't reachable. Stamp a deterministic placeholder.
		orderID = "SBX-" + id
		if _, err := h.DB.Exec(ctx,
			`UPDATE payments SET provider='paypal', provider_order_id=$1 WHERE id=$2`,
			orderID, id); err != nil {
			writeErr(w, 500, err.Error())
			return
		}
	}

	captureID := "SBX-CAPTURE-" + strings.ToUpper(id[:8])
	eventID := "SBX-EVT-" + fmt.Sprintf("%d", time.Now().UnixNano())
	payload := fmt.Sprintf(`{"id":%q,"event_type":"PAYMENT.CAPTURE.COMPLETED","resource":{"id":%q,"supplementary_data":{"related_ids":{"order_id":%q}}},"sandbox_simulated":true}`,
		eventID, captureID, orderID)

	if _, err := h.DB.Exec(ctx, `
		INSERT INTO payment_webhook_events
		    (provider, event_id, event_type, payload, signature_ok, processed_at)
		VALUES ('paypal',$1,'PAYMENT.CAPTURE.COMPLETED',$2::jsonb,true,NOW())`,
		eventID, payload); err != nil {
		writeErr(w, 500, "log webhook: "+err.Error())
		return
	}

	// Reconcile within a transaction (same path as the real webhook handler).
	tx, err := h.DB.Begin(ctx)
	if err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	defer tx.Rollback(ctx)
	if _, err := tx.Exec(ctx, `
		UPDATE payments
		   SET status='completed', paid_at=NOW(), provider_capture_id=$1,
		       metadata = COALESCE(metadata, '{}'::jsonb) || jsonb_build_object('sandbox', true, 'sandbox_webhook', true)
		 WHERE id=$2 AND status<>'completed'`, captureID, id); err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	if err := reconcileInvoice(ctx, tx, id); err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	if err := tx.Commit(ctx); err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	writeJSON(w, 200, map[string]any{
		"status":     "completed",
		"event_id":   eventID,
		"capture_id": captureID,
		"order_id":   orderID,
	})
}

// AdminList returns invoices flagged sandbox=true so admins can clean up
// or review test data. Includes the test customer's invoices regardless
// of the flag so legacy seeds are still visible.
func (h *SandboxHandler) AdminList(w http.ResponseWriter, r *http.Request) {
	if _, any := GetAllMethodModes(r.Context(), h.DB); !any {
		writeErr(w, 403, "no payment methods are in sandbox mode")
		return
	}
	ctx := r.Context()
	rows, err := h.DB.Query(ctx, `
		SELECT i.id, i.invoice_number, i.status, i.total_cents, i.amount_paid_cents,
		       i.currency, i.created_at, c.name
		  FROM invoices i JOIN customers c ON c.id=i.customer_id
		 WHERE (i.metadata ? 'sandbox') OR c.slug='sandbox-test'
		 ORDER BY i.created_at DESC LIMIT 100`)
	if err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	defer rows.Close()
	out := []map[string]any{}
	for rows.Next() {
		var (
			id, number, status, currency, customer string
			total, paid                            int64
			created                                time.Time
		)
		if err := rows.Scan(&id, &number, &status, &total, &paid, &currency, &created, &customer); err != nil {
			writeErr(w, 500, err.Error())
			return
		}
		out = append(out, map[string]any{
			"id":                id,
			"invoice_number":    number,
			"status":            status,
			"total_cents":       total,
			"amount_paid_cents": paid,
			"currency":          currency,
			"created_at":        created,
			"customer_name":     customer,
		})
	}
	writeJSON(w, 200, out)
}

// AdminListPayments lists pending sandbox payments so admins can pick
// one to complete or simulate a webhook for.
func (h *SandboxHandler) AdminListPayments(w http.ResponseWriter, r *http.Request) {
	if _, any := GetAllMethodModes(r.Context(), h.DB); !any {
		writeErr(w, 403, "no payment methods are in sandbox mode")
		return
	}
	ctx := r.Context()
	rows, err := h.DB.Query(ctx, `
		SELECT p.id, p.payment_number, p.invoice_id, p.method, p.status,
		       p.amount_cents, p.currency, p.provider_order_id,
		       i.invoice_number, c.name, p.created_at
		  FROM payments p
		  JOIN invoices i ON i.id=p.invoice_id
		  JOIN customers c ON c.id=p.customer_id
		 WHERE p.status IN ('pending','awaiting_verification')
		   AND ((i.metadata ? 'sandbox') OR c.slug='sandbox-test')
		 ORDER BY p.created_at DESC LIMIT 100`)
	if err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	defer rows.Close()
	out := []map[string]any{}
	for rows.Next() {
		var (
			id, number, invoiceID, method, status, currency string
			orderID                                         *string
			invNumber, customer                             string
			amount                                          int64
			created                                         time.Time
		)
		if err := rows.Scan(&id, &number, &invoiceID, &method, &status, &amount, &currency, &orderID,
			&invNumber, &customer, &created); err != nil {
			writeErr(w, 500, err.Error())
			return
		}
		out = append(out, map[string]any{
			"id":             id,
			"payment_number": number,
			"invoice_id":     invoiceID,
			"invoice_number": invNumber,
			"customer_name":  customer,
			"method":         method,
			"status":         status,
			"amount_cents":   amount,
			"currency":       currency,
			"order_id":       orderID,
			"created_at":     created,
		})
	}
	writeJSON(w, 200, out)
}

// AdminPurge deletes every invoice + payment row marked sandbox. Useful
// to reset the test environment without dropping the database. Refuses
// to operate when mode != 'sandbox' as a safety belt.
func (h *SandboxHandler) AdminPurge(w http.ResponseWriter, r *http.Request) {
	if _, any := GetAllMethodModes(r.Context(), h.DB); !any {
		writeErr(w, 403, "no payment methods are in sandbox mode")
		return
	}
	ctx, cancel := makeCtx()
	defer cancel()
	tx, err := h.DB.Begin(ctx)
	if err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	defer tx.Rollback(ctx)

	var ids []string
	rows, err := tx.Query(ctx, `
		SELECT i.id
		  FROM invoices i
		  LEFT JOIN customers c ON c.id=i.customer_id
		 WHERE (i.metadata ? 'sandbox') OR c.slug='sandbox-test'`)
	if err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			rows.Close()
			writeErr(w, 500, err.Error())
			return
		}
		ids = append(ids, id)
	}
	rows.Close()

	if len(ids) == 0 {
		_ = tx.Commit(ctx)
		writeJSON(w, 200, map[string]int{"deleted": 0})
		return
	}
	if _, err := tx.Exec(ctx, `DELETE FROM payments WHERE invoice_id = ANY($1)`, ids); err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	if _, err := tx.Exec(ctx, `DELETE FROM invoices WHERE id = ANY($1)`, ids); err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	if err := tx.Commit(ctx); err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	writeJSON(w, 200, map[string]int{"deleted": len(ids)})
}

// Compile-time guard so unused imports don't break the build when the
// sandbox feature set evolves.
var _ = json.Unmarshal
