-- 068_assethub_backfill_asset_tags.sql
-- Backfill default asset tags onto devices that predate 067. The auto-assign in
-- handlers/assettag.go (assignAssetTagIfEmpty) only fires on ingest, so devices
-- already in the register keep a NULL tag until re-ingested or regenerated by
-- hand. This assigns them now, using the SAME scheme as the Go generator:
--
--   PREFIX-CCC-SSS-NNN   e.g.  DPV-001-002-001
--     PREFIX = customers.asset_tag_prefix   (backfilled in 067; 'F2' fallback)
--     CCC    = category code (device_type)
--     SSS    = sub-type (computers: laptop 002 / desktop 001; others 000)
--     NNN    = running number, per (org, category), zero-padded to 3, stable
--              by created_at so re-runs and re-ingests stay deterministic.
--
-- Only touches devices with no tag; explicit/manual tags are left untouched.
-- Numbering starts from the current counter value per (org, category), so it
-- never collides with tags already issued by post-067 ingests. Idempotent:
-- re-running finds nothing to tag and re-derives the counter to the same value.

WITH cat AS (
    SELECT d.id,
           d.customer_id,
           d.created_at,
           CASE lower(COALESCE(d.device_type, 'unknown'))
               WHEN 'computer' THEN '001' WHEN 'server'  THEN '002' WHEN 'nas'    THEN '003'
               WHEN 'router'   THEN '004' WHEN 'switch'  THEN '005' WHEN 'ap'     THEN '006'
               WHEN 'printer'  THEN '007' WHEN 'camera'  THEN '008' WHEN 'phone'  THEN '009'
               WHEN 'tablet'   THEN '010' WHEN 'iot'     THEN '011'
               ELSE '099'
           END AS cc,
           CASE
               WHEN lower(COALESCE(d.device_type, '')) <> 'computer' THEN '000'
               WHEN lower(COALESCE(d.model, '') || ' ' || COALESCE(d.os_name, '')) ~ '(book|laptop|notebook)' THEN '002'
               ELSE '001'
           END AS sc
      FROM assethub_devices d
     -- NULL, empty, OR any legacy/non-canonical tag (e.g. old 3-segment
     -- PREFIX-CCC-NNN, or duplicates). Tags already in the new 4-segment
     -- scheme are left exactly as they are.
     WHERE d.asset_tag IS NULL
        OR d.asset_tag = ''
        OR d.asset_tag !~ '^[A-Za-z0-9]+-[0-9]{3}-[0-9]{3}-[0-9]{3,}$'
),
numbered AS (
    SELECT c.id,
           c.customer_id,
           c.cc,
           c.sc,
           -- continue from the counter (or 1 if none), so we never reuse a
           -- number already issued to a post-067 auto-tagged device.
           COALESCE(s.next_val, 1)
             + ROW_NUMBER() OVER (PARTITION BY c.customer_id, c.cc ORDER BY c.created_at, c.id)
             - 1 AS nnn
      FROM cat c
      LEFT JOIN assethub_asset_seq s
             ON s.customer_id = c.customer_id AND s.category_code = c.cc
)
UPDATE assethub_devices dev
   SET asset_tag = COALESCE(NULLIF(cu.asset_tag_prefix, ''), 'F2')
                   || '-' || n.cc || '-' || n.sc
                   || '-' || lpad(n.nnn::text, 3, '0'),
       updated_at = NOW()
  FROM numbered n
  JOIN customers cu ON cu.id = n.customer_id
 WHERE dev.id = n.id;

-- Advance the per-(org, category) counter to max issued + 1 so the Go generator
-- picks up exactly where the backfill left off. Reads back the numbers straight
-- from the freshly written tags, so it self-corrects regardless of how they got
-- there. GREATEST guards against lowering an already-higher counter.
INSERT INTO assethub_asset_seq (customer_id, category_code, next_val)
SELECT customer_id,
       split_part(asset_tag, '-', 2)            AS category_code,
       MAX(split_part(asset_tag, '-', 4)::int) + 1 AS next_val
  FROM assethub_devices
 WHERE asset_tag ~ '^[A-Za-z0-9]+-[0-9]{3}-[0-9]{3}-[0-9]{3,}$'
 GROUP BY customer_id, split_part(asset_tag, '-', 2)
ON CONFLICT (customer_id, category_code)
DO UPDATE SET next_val = GREATEST(assethub_asset_seq.next_val, EXCLUDED.next_val);
